import "./globals.css";
import Image from "next/image";
import Nav from "@/components/Nav";

export const metadata = {
  title: "Mi biblioteca personal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="header">
          <Image
            src="/images/logo_cuervo.png"
            alt="Cuervo Biblioteca"
            width={40}
            height={40}
            className="header__logo"
          />
          <h1 className="header__title">Cuervo Biblioteca</h1>
        </header>

        <Nav />
        <main>{children}</main>
        <footer>ESTO ES UN FOOTER</footer>
      </body>
    </html>
  );
}